version: 2

linters:
  enable:
    - bodyclose
    - exhaustive
    - goconst
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wrapcheck

formatters:
  enable:
    - gofumpt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - wrapcheck

run:
  timeout: 5m
