// Command climd renders the full aps command reference — every
// available command, its synopsis, flags, and intra-page links — from
// the live cobra command tree exposed by internal/cli. Invoked by the
// cog marker embedded in docs/cli/commands.md (see `make docs-gen`);
// never run in production paths.
package main

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"hop.top/aps/internal/cli"
)

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(args []string, stdout, stderr io.Writer) int {
	if len(args) != 0 {
		_, _ = fmt.Fprintln(stderr, "usage: climd")
		return 2
	}
	out, err := render(cli.RootCommand())
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "rendering command reference: %v\n", err)
		return 1
	}
	_, _ = fmt.Fprint(stdout, out)
	return 0
}

// anchorLink rewrites cobra's per-file markdown links
// ("aps_profile_create.md") into intra-page heading anchors
// ("#aps-profile-create") so the single-page reference self-links.
func anchorLink(link string) string {
	return "#" + strings.ReplaceAll(strings.TrimSuffix(link, ".md"), "_", "-")
}

// render walks the command tree depth-first (children sorted by name)
// and concatenates cobra's markdown page for each available command
// into one deterministic document.
func render(root *cobra.Command) (string, error) {
	var b strings.Builder
	var walk func(cmd *cobra.Command) error
	walk = func(cmd *cobra.Command) error {
		// The dated "Auto generated by spf13/cobra" footer would go
		// stale daily and trip the docs-check staleness gate.
		cmd.DisableAutoGenTag = true
		if err := doc.GenMarkdownCustom(cmd, &b, anchorLink); err != nil {
			return fmt.Errorf("rendering %q: %w", cmd.CommandPath(), err)
		}
		children := append([]*cobra.Command(nil), cmd.Commands()...)
		sort.Slice(children, func(i, j int) bool {
			return children[i].Name() < children[j].Name()
		})
		for _, child := range children {
			if !child.IsAvailableCommand() || child.IsAdditionalHelpTopicCommand() {
				continue
			}
			if err := walk(child); err != nil {
				return err
			}
		}
		return nil
	}
	if err := walk(root); err != nil {
		return "", err
	}
	return b.String(), nil
}
