package main

import (
	"bytes"
	"os"
	"strings"
	"testing"

	"hop.top/aps/internal/cli"
)

func renderOrFail(t *testing.T) string {
	t.Helper()
	out, err := render(cli.RootCommand())
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	return out
}

func TestRenderCoversEveryTopLevelCommand(t *testing.T) {
	out := renderOrFail(t)
	if !strings.HasPrefix(out, "## aps\n") {
		t.Errorf("output does not start with the root command page:\n%.120s", out)
	}
	for _, child := range cli.RootCommand().Commands() {
		if !child.IsAvailableCommand() || child.IsAdditionalHelpTopicCommand() {
			continue
		}
		heading := "\n## aps " + child.Name() + "\n"
		if !strings.Contains(out, heading) {
			t.Errorf("missing page for top-level command %q", child.Name())
		}
	}
}

func TestRenderStableOutput(t *testing.T) {
	first := renderOrFail(t)
	for i := 0; i < 3; i++ {
		if again := renderOrFail(t); again != first {
			t.Fatal("unstable output across renders")
		}
	}
}

// The dated cobra footer would trip `make docs-check` the day after
// every regen; render must strip it from every page.
func TestRenderHasNoAutoGenTag(t *testing.T) {
	if strings.Contains(renderOrFail(t), "Auto generated by spf13/cobra") {
		t.Error("output contains the dated spf13/cobra auto-gen footer")
	}
}

// Flag defaults or synopses that embed the current user's paths would
// make the committed reference differ per machine and fail the
// staleness gate in CI.
func TestRenderHasNoMachinePaths(t *testing.T) {
	home, err := os.UserHomeDir()
	if err != nil {
		t.Skipf("no home dir: %v", err)
	}
	if strings.Contains(renderOrFail(t), home) {
		t.Errorf("output embeds the local home dir %q", home)
	}
}

func TestAnchorLink(t *testing.T) {
	if got := anchorLink("aps_profile_create.md"); got != "#aps-profile-create" {
		t.Errorf("anchorLink = %q, want %q", got, "#aps-profile-create")
	}
}

func TestRunNoArgsExitsZero(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if code := run(nil, &stdout, &stderr); code != 0 {
		t.Fatalf("run() exit code %d, stderr: %s", code, stderr.String())
	}
	if stdout.Len() == 0 {
		t.Fatal("run() wrote nothing to stdout")
	}
}

func TestRunWithArgsExitsNonZero(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if code := run([]string{"bogus"}, &stdout, &stderr); code == 0 {
		t.Fatal("run with arguments returned exit code 0")
	}
	if !strings.Contains(stderr.String(), "usage:") {
		t.Errorf("stderr missing usage line: %q", stderr.String())
	}
}
